#!/bin/sh

# PROVIDE: nasd
# REQUIRE: DAEMON
# BEFORE:  LOGIN

. /etc/rc.subr

name="nasd"
rcvar=`set_rcvar`
command="/usr/local/bin/nasd"

load_rc_config $name

: ${nasd_enable="NO"}
: ${nasd_flags="-aa -b"}

run_rc_command "$1"
